# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# HOW TO USE:
# install PyQt5 by typing pip install pyqt5 into cmd
# run as usual :>

from PyQt5 import QtCore, QtGui, QtWidgets
import lexical_analyzer3 as la, semantics_analyzer as sea, syntax_analyzer as sya

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.code_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.code_input.setGeometry(QtCore.QRect(10, 10, 381, 261))
        self.code_input.setObjectName("code_input")
        self.lexemes_label = QtWidgets.QLabel(self.centralwidget)
        self.lexemes_label.setGeometry(QtCore.QRect(450, 0, 91, 31))
        self.lexemes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lexemes_label.setObjectName("lexemes_label")
        self.code_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.code_output.setGeometry(QtCore.QRect(10, 310, 781, 241))
        self.code_output.setObjectName("code_output")
        self.execute_button = QtWidgets.QPushButton(self.centralwidget)
        self.execute_button.setGeometry(QtCore.QRect(10, 280, 781, 23))
        self.execute_button.setObjectName("execute_button")
        self.symboltable_label = QtWidgets.QLabel(self.centralwidget)
        self.symboltable_label.setGeometry(QtCore.QRect(650, 0, 91, 31))
        self.symboltable_label.setAlignment(QtCore.Qt.AlignCenter)
        self.symboltable_label.setObjectName("symboltable_label")
        self.lexemes_list = QtWidgets.QTableWidget(self.centralwidget)
        self.lexemes_list.setGeometry(QtCore.QRect(400, 30, 191, 241))
        self.lexemes_list.setColumnCount(2)
        self.lexemes_list.setObjectName("lexemes_list")
        self.lexemes_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lexemes_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lexemes_list.setHorizontalHeaderItem(1, item)
        self.symboltable_list = QtWidgets.QTableWidget(self.centralwidget)
        self.symboltable_list.setGeometry(QtCore.QRect(600, 30, 191, 241))
        self.symboltable_list.setColumnCount(2)
        self.symboltable_list.setObjectName("symboltable_list")
        self.symboltable_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.symboltable_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.symboltable_list.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.execute_button.clicked.connect(self.execute_clicked)
        # self.actionOpen.triggered.connect(self.openFileNameDialog)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOLCode Interpreter - Team Kanin"))
        MainWindow.setAccessibleName(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lexemes_label.setText(_translate("MainWindow", "Lexemes"))
        self.execute_button.setText(_translate("MainWindow", "Execute"))
        self.symboltable_label.setText(_translate("MainWindow", "Symbol Table"))
        item = self.lexemes_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lexeme"))
        item = self.lexemes_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Classification"))
        item = self.symboltable_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Identifier"))
        item = self.symboltable_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

    def execute_clicked(self, MainWindow):

        while self.lexemes_list.rowCount() > 0:
            self.lexemes_list.removeRow(0)

        while self.symboltable_list.rowCount() > 0:
            self.symboltable_list.removeRow(0)

        code = self.code_input.toPlainText()
        lexemes = la.LexicalAnalyzer(code)

        for i in range(0, len(lexemes[1])):
            self.lexemes_list.insertRow(i)
            self.lexemes_list.setItem(i,0,QtWidgets.QTableWidgetItem(lexemes[1][i].lexeme))
            self.lexemes_list.setItem(i,1,QtWidgets.QTableWidgetItem(lexemes[1][i].type))
        
        symbol_table = sya.SyntaxAnalyzer(lexemes[0],lexemes[1])

        for i in range(0, len(symbol_table[2])):
            self.symboltable_list.insertRow(i)
            self.symboltable_list.setItem(i,0,QtWidgets.QTableWidgetItem(symbol_table[2][i][0]))
            if isinstance(symbol_table[2][i][2], str):
                self.symboltable_list.setItem(i,1,QtWidgets.QTableWidgetItem(symbol_table[2][i][2]))
            else:
                self.symboltable_list.setItem(i,1,QtWidgets.QTableWidgetItem("to be evaluated"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())

